PMIS/ViewModels/PrescriptionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PMIS.ViewModels
{
    public class PrescriptionViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter category")]
        public int PrescriptionCatid { get; set; }

        public string PrescriptionCatDetails { get; set; }
        [Required(ErrorMessage = "Please enter category")]
        public string PrescriptionDetails { get; set; }
        [Required(ErrorMessage = "Please enter category")]
        public string PrescUnit { get; set; }
        public IEnumerable<SelectListItem> PresCategorySelectList { get; set;}
    }
}

PMIS/Controllers/PrescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PMIS.Model;
using PMIS.ServiceLayer;
using PMIS.ViewModels;

namespace PMIS.Controllers
{
    public class PrescriptionController : Controller
    {
        private readonly IPrescriptionServices _prescriptionServices;
        private readonly IPatientRecordServices _patientRecordServices;
        private readonly IPatientServices _patientServices;
        private readonly IUnitOfWork _unitOfWork;
        public PrescriptionController(IPrescriptionServices prescriptionServices, IUnitOfWork unitOfWork, IPatientRecordServices patientRecordServices, IPatientServices patientServices)
        {
            _prescriptionServices = prescriptionServices;
            _unitOfWork = unitOfWork;
            _patientRecordServices = patientRecordServices;
            _patientServices = patientServices;
        }
        // GET: Prescription
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetAllPrescriptionsAsync()
        {
            var prescriptionlist = await _prescriptionServices.GetAllPrescriptions();
            return Json(new {data=prescriptionlist},JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreatePrescription()
        {
            var prescription=new PrescriptionViewModel
            {
                PresCategorySelectList = _prescriptionServices.GetCategoryListItems()
            };

            return PartialView("_CreatePrescription",prescription);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePrescription(PrescriptionViewModel prescriptionviewmodel)
        {
            if (!ModelState.IsValid)
            {
              return PartialView("_CreatePrescription", prescriptionviewmodel);
            }

            var prescription=new Prescription()
            {
                CatId = prescriptionviewmodel.PrescriptionCatid,
                PrescriptionDetails = prescriptionviewmodel.PrescriptionDetails,
                Unit = prescriptionviewmodel.PrescUnit
            };
            _prescriptionServices.InsertPrescription(prescription);
            _unitOfWork.Commit();

            return Json(new {success=true},JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> RemovePrescription(int id)
        {
            var prescription =await _prescriptionServices.GetPrescriptionByIdAsync(id);
            if (prescription != null)
            {
                _prescriptionServices.RemovePrescription(prescription);
                _unitOfWork.Commit();

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new {success = false}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> PrintPrescript(int medRecNo)
        {
            //var reportOption = new ReportOptionViewModel()
            //{
            //   recordNo = medRecNo
            //};

            var medicalRecordList = await _patientRecordServices.GetAllRecordsAsync();
            ContainerClass.MedicalRecord = (from m in medicalRecordList where m.RecordNo==medRecNo
                                            select new PrintMedicalRecordViewModel()
                                            {
                                                RecordNo = (int)m.RecordNo,
                                                PatientId = m.Pat_Id,
                                                PatFullname = m.Patient.Firstname +' ' + m.Patient.Lastname,
                                                PatAddress=m.Patient.Muncity + ' ' + m.Patient.Province,
                                                PhyId = m.Phys_id,
                                                RecordedDate = (DateTime) m.RecordDate,
                                                Gender= m.Patient.Gender[0],
                                                Age=HelperClass.Utilities.GetAge((System.DateTime)m.Patient.DoB)


                                            }).ToList();

           var docprescription = _prescriptionServices.GetDocPrescriptionByRecNo(medRecNo).ToList();
            ContainerClass.DocPrescription = (from p in docprescription
                                               select new PrintDocPrescriptionViewModel()
                                                {
                                                    PrescNo = p.PrescNo,
                                                    RecNo = p.RecNo,
                                                    PrescriptionDetails = p.PrescriptionDetails,
                                                    Sig = p.Sig,
                                                    DispInst = p.DispInst

                                                }).ToList();

           var patientList = await _patientServices.GetAllPatients();
            ContainerClass.PatientDetails = patientList.Where(t => t.PatientId == ContainerClass.MedicalRecord[0].PatientId).ToList();

            return View("~/Views/Shared/ReportContainer.cshtml");
        }
    }
} 

PMIS/Views/Prescription/Index.cshtml
<div class="row">
    <div class="col-lg">
        <div class="card" style="min-height: 530px;">
            <div class="card-header">
                <h3 class="card-title">Prescription</h3>
            </div>
            <div class="card-body h-100">
                <div class="table-responsive">
                    <table class="table table-striped table-sm table-bordered compact nowrap" id="tblePrescription">
                        <thead class="bg-cyan">
                        <tr>
                            <th></th>
                            <th class="text-center">ID</th>
                            <th class="text-center">CATEGORY</th>
                            <th class="text-center">DESCRIPTION</th>
                            <th class="text-center">MAKE</th>


                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-createprescription">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create/Update Prescription</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->


@section scripts
{
   @Scripts.Render("~/Scripts/js_prescription.js")
}

PMIS/Views/Prescription/_CreatePrescription.cshtml
@using PMIS.ViewModels
@model PrescriptionViewModel

<div class="container-fluid">

    <div class="alert alert-info alert-dismissible">
        <h6><i class="icon fas fa-info"></i>Note:</h6>
        <p class="text" style="margin-bottom: 0; padding-bottom: 0;">All fields marked with an * are required</p>
    </div>

    @using (Html.BeginForm("CreatePrescription", "Prescription", FormMethod.Post, new { @role = "form", @id = "formprescription" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(m=>m.Id)
        
        <div class="row">
            <div class="col-lg">

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label required">Category:</label>
                    <div class="col-sm-6">
                        @Html.DropDownListFor(m => m.PrescriptionCatid, Model.PresCategorySelectList, "-------Select Category------", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PrescriptionCatid, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label required">Details:</label>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(m=>m.PrescriptionDetails,new {@class="form-control",@rows=2, @placeholder = "Prescription Details"})
                        @Html.ValidationMessageFor(m => m.PrescriptionDetails, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label required">Unit:</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m=>m.PrescUnit,new {@class="form-control"})
                        @Html.ValidationMessageFor(m => m.PrescUnit, null, new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 offset-md-4">
                <button type="button" class="btn btn-primary" id="btn-savePrescription">Save </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
        </div>
    }

</div>