PMIS/ViewModels/PatientProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using PMIS.Model;

namespace PMIS.ViewModels
{
    public class PatientProfileViewModel
    {
        public string PatientId { get; set; }
        public PatientDetailsViewModel PatientDetails { get; set; }
        public List<PhysicianDetailsViewModel> Listofdoctors { get; set; }
        public Appointment Lastvisited { get; set; }

       
    }
}

PMIS/Areas/Doctor/Controllers/PatientMedicalRecordController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Services.Configuration;
using Microsoft.AspNet.Identity;
using PMIS.Model;
using PMIS.ServiceLayer;
using PMIS.ViewModels;
using PagedList;
using PMIS.HelperClass;
using System.Collections.Generic;

namespace PMIS.Areas.Doctor.Controllers
{
   [UserPermissionAuthorized(UserPermisionLevelEnum.doctor)]
    public class PatientMedicalRecordController : Controller
    {
        private readonly IPatientRecordServices _patientrecordservices;
        private readonly IPatientServices _patientservices;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPrescriptionServices _prescriptionServices;
        private readonly IPhyPrescriptionServices _phyPrescriptionServices;
        public PatientMedicalRecordController(IPatientRecordServices patientrecordservices, IPatientServices patientservices, IUnitOfWork unitOfWork, IPrescriptionServices prescriptionServices, IPhyPrescriptionServices phyPrescriptionServices)
        {
            _patientrecordservices = patientrecordservices;
            _patientservices = patientservices;
            _unitOfWork = unitOfWork;
            _prescriptionServices = prescriptionServices;
            _phyPrescriptionServices = phyPrescriptionServices;
        }
        // GET: Doctor/PatientMedicalRecord
        public ActionResult Index()
        {
            ViewBag.loginPhyId =HttpContext.User.Identity.GetUserId();
            return View();
        }

        [HttpGet]
        public ActionResult MedicalHistory(string id,string phyid,int? page)
        {
            int pageIndex = page ?? 1;
            int dataCount = 3;
           

            ViewBag.patId = id;
            ViewBag.phyId = phyid;
           


            var patientRecordDetails = new PatientMedicalRecordDetailsViewModel
            {
                PatientId = id,
                PhyId = phyid,
                Patient = _patientservices.GetPatientById(id)
             };
            var medicalRecord = _patientrecordservices.GetAllRecords(id, phyid);

            patientRecordDetails.MedicalRecordList = medicalRecord.OrderByDescending(t => t.RecordNo).ToList()
                .ToPagedList(pageIndex, dataCount);
          
            if (Request.IsAjaxRequest())
            {
                return PartialView("_RecordListPartialView",(PagedList<MedicalRecord>) patientRecordDetails.MedicalRecordList);
            }
         
            return View(patientRecordDetails);
        }



        [HttpGet]
        public ActionResult New_MedicalRecord(string id)
        {
            //var userid = System.Web.HttpContext.Current.User.Identity.GetUserId();


            var newrecord = new MedicalRecordViewModel()
            {
                PatientId = id,
                //PhyId =
            };


            return PartialView("_AddPatientRecordPartialView",newrecord);
        }


        [HttpGet]
        public ActionResult CreateMedication(int recNo)
        {

            var medication = _patientrecordservices.GetMedication(recNo);

            var medicationModel = new MedicationViewModel()
            {

                RecordNo = recNo,
                RecordedDate = DateTime.Now,
                Medication = medication != null ? medication.MedicationDesc : String.Empty
            };

            if (medication != null)
            {
                medicationModel.operation = 1;
                medicationModel.Id = (int)medication.MidNo;
            }
            else
            {
                medicationModel.operation = 0;
            }

            //medicationModel.operation = medication != null ? 1 : 0;

            return PartialView("_CreateMedication", medicationModel);
        }

        [HttpGet]
        public async Task<ActionResult> GetRecordChart(int recordNo)
        {

            var medicalRecord = await _patientrecordservices.GetMedicalRecord(recordNo);

            return PartialView("_GetRecord", medicalRecord);
        }

        [HttpGet]
        public ActionResult GetMedicationView(int recNo)
        {
            var patientMedication = _patientrecordservices.GetMedication(recNo);
            
            return PartialView("_GetMedicationView", patientMedication);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMedication(MedicationViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_CreateMedication", viewModel);
            }


            Medication medication = new Medication
            {
                MidNo = viewModel.Id,
                RecordNo = viewModel.RecordNo,
                RecordedDate = DateTime.Now,
                MedicationDesc = viewModel.Medication
            };

            if (viewModel.operation == 0)
            {
                _patientrecordservices.AddMedication(medication);
            }
            else
            {
                _patientrecordservices.UpdateMedication(medication);
            }

            _unitOfWork.Commit();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ModifyRecord(int recNo)
        {

            return PartialView("_ModifyPatientRecord");
        }


        public async Task<ActionResult> RemoveMedicationAsync(int medNo)
        {

            var medication = await _patientrecordservices.GetMedicationBymedNo(medNo);

            if (medication == null) return Json(new { succces = false }, JsonRequestBehavior.AllowGet);


            _patientrecordservices.RemoveMedication(medication);

            _unitOfWork.Commit();

            return Json(new {success = true}, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult MedicalPrescription(int recNo)
        {
            var docPrescription=new DocPrescriptionViewModel
            {   

                RecNo = recNo,
                PrescriptionCatListItem = _prescriptionServices.GetCategoryListItems(),
                RecipeListItem = _prescriptionServices.GetPrescriptionListItems(null)
            };


            return PartialView("_MedicalPrescription", docPrescription);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("AddNewDoctorsPrescription")]
        public ActionResult MedicalPrescription(DocPrescriptionViewModel docPrescriptionViewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_MedicalPrescription", docPrescriptionViewModel);
            }

            var docprescription=new DocPrescriptionRecord()
            {
                Date =DateTime.Now,
                RecordNo = docPrescriptionViewModel.RecNo,
                PresId = docPrescriptionViewModel.PrescId,
                Sig = docPrescriptionViewModel.Sig,
                Disp = docPrescriptionViewModel.DispInst
            };

            _phyPrescriptionServices.InsertDocPrescription(docprescription);
            _unitOfWork.Commit();

            return Json(new {success=true}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ModifyMedicalPrescription(int prescNo)
        {
            var docprescription =_phyPrescriptionServices.FindDocPrescriptionById(prescNo);

            DocPrescriptionViewModel docPrescriptionViewModel=null;
            if (docprescription != null)
            {
                docPrescriptionViewModel = new DocPrescriptionViewModel()
                {
                    PrescNo = prescNo,
                    RecNo = (int) docprescription.RecordNo,
                    CatId = (int) docprescription.Prescription.CatId,
                    PrescId = (int) docprescription.PresId,
                    Sig = docprescription.Sig,
                    DispInst = docprescription.Disp,
                    PrescriptionCatListItem= _prescriptionServices.GetCategoryListItems(),
                    RecipeListItem = _prescriptionServices.GetPrescriptionListItems((int)docprescription.Prescription.CatId)
                };

             
            }

            return PartialView("_ModifyMedicalPrescription", docPrescriptionViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMedicalPrescription(DocPrescriptionViewModel docPrescriptionViewModel)
        {
            if (!ModelState.IsValid) return PartialView("_ModifyMedicalPrescription", docPrescriptionViewModel);

            var docprescription = new DocPrescriptionRecord()
            {
                Date = DateTime.Now,
                No = docPrescriptionViewModel.PrescNo,
                RecordNo = docPrescriptionViewModel.RecNo,
                PresId = docPrescriptionViewModel.PrescId,
                Sig = docPrescriptionViewModel.Sig,
                Disp = docPrescriptionViewModel.DispInst
            };

            _phyPrescriptionServices.UpdateDocPrescription(docprescription);
            _unitOfWork.Commit();

            return Json(new {success=true}, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ActionName("RemoveDoctorsPrescription")]
        public async Task<ActionResult> RemoveMedicalPrescription(int prescNo)
        {
            var docprescription =await _phyPrescriptionServices.FindDocPrescriptionByIdAsync(prescNo);


            if (docprescription == null) return Json(new {succces = false}, JsonRequestBehavior.AllowGet);

            _phyPrescriptionServices.RemoveDocPrescription(docprescription);
            _unitOfWork.Commit();

            return Json(new { succces = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetMedPrescription(int recordNo)
        {
            var docprescriptionList = _prescriptionServices.GetDocPrescriptionByRecNo(recordNo);

PMIS/Areas/Doctor/Views/PatientMedicalRecord/Index.cshtml
<input id="hdnLogPhyId" type="hidden" value="@ViewBag.loginPhyId" />
<div class="container">
    <div class="row">
        <div class="col-lg">
            <div class="card" style="min-height: 160px;">
                <div class="card-body">
                    <div class="col-md-6 offset-3 mt-5 ">
                        <input type="text" class="form-control" placeholder="Search Patient Firstname or Lastname" id="search-patient">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg" id="patient-physList">

        </div>
    </div>
</div>




@section scripts
{
  
    <script type="text/javascript">

       


        var patMedicalRecord = {

            getMedicalRecordByDoc: "@Url.Action("MedicalHistory","PatientMedicalRecord",new {area="Doctor", id = "patid", phyid = "phid"})"

        }
          


    </script>

   @Scripts.Render("~/Areas/Scripts/js_doc_medicalrecords.js")
}

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_AddPatientRecordPartialView.cshtml
@using PMIS.ViewModels
@model MedicalRecordViewModel
    

<div class="container-fluid">
    @using (Html.BeginForm("AddRecordAsync", "PatientRecord",FormMethod.Post,new {@role="form",@id="formPatientRecord"}))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m=>m.PatientId)
        @Html.HiddenFor(m=>m.PhyId)
        <div class="row">
            <div class="col-lg">
            
                <div class="form-group">
                  @Html.TextBoxFor(m=>m.Subject,new {@class="form-control",@placeholder="Subject"})
                </div>
            
                <div class="form-group">
                  
                    @Html.TextAreaFor(m=>m.Desciption,new {@class= "form-control", @id="compose-record",rows="5",style="resize:none;"})
                </div>
            </div>
       
        </div>
        <div class="row">
            <div class="col-lg-5 offset-5">
                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Discard</button>
                <button type="submit" class="btn btn-primary" id="save-record"><i class="far fa-envelope"></i> Save </button>
            </div>
        </div>

    }
</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_CreateMedication.cshtml
@using PMIS.ViewModels
@model MedicationViewModel

<div class="container-fluid" style="min-height: 350px;">
    
    @using (Html.BeginForm("CreateMedication", "PatientMedicalRecord", FormMethod.Post, new { role = "form", id = "form_docAddMedication"}))
    {

        @Html.AntiForgeryToken()

        @Html.HiddenFor(m=>m.Id)
        @Html.HiddenFor(m=>m.RecordNo,new {@id="recNo"})
        @Html.HiddenFor(m=>m.operation)

        <div class="row">
            <div class="col-lg">

                <div class="form-group">

                    @Html.TextAreaFor(m => m.Medication, new {@class = "form-control", @id = "compose-medication", rows = "5", style = "resize:none;"})
                </div>


            </div>
        </div>

        <div class="row">
            <div class="col-lg-5 offset-5">
                <button type="submit" class="btn btn-primary" id="save-docmedication"><i class="far fa-envelope"></i> Save </button>
                <button type="reset" class="btn btn-default" id="modalClose"><i class="fas fa-times"></i> Discard</button>

            </div>
        </div>
    }
   

</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_GetMedicalChartDetail.cshtml
@using PMIS.ViewModels
@model MedicalRecordViewModel

<div class="container-fluid" style="min-height: 350px;">

@using (Html.BeginForm("UpdateMedicalRecord", "PatientMedicalRecord", FormMethod.Post, new { role = "form", id = "update-medicalchartRecord" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.RecordNo)
    @Html.HiddenFor(m => m.PatientId)
    @Html.HiddenFor(m => m.PhyId)
    @Html.HiddenFor(m=> m.ApppointmentNo)
    @Html.HiddenFor(m=>m.Subject)
    <div class="row">
        <div class="col-lg">

            <div class="form-group">
               @Html.TextAreaFor(m => m.Desciption, new { @class = "form-control", id = "compose-medicalrecord", rows = "15", style = "resize:none;" })
            </div>


        </div>
    </div>
    <div class="row">
        <div class="col-lg-5 offset-5">
            <button type="submit" class="btn btn-primary" id="save-medicalchart-record"><i class="far fa-envelope"></i> Save </button>
        </div>
    </div>
}
</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_GetMedicationView.cshtml
@using PMIS.Model
@model Medication



@if (Model != null)
{
    <input type="hidden" value="@Model.MidNo" id="medicationNo" />

    @(new HtmlString(Model.MedicationDesc))
}
else
{
    <div style="height:40px;">
        <p style="margin-left:20px;color:#ff0000;text-align:center;font-size:15px;"> No medication found</p>
    </div>
}

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_GetRecord.cshtml
@using PMIS.Model
@model MedicalRecord

<input type="hidden" value="@ViewBag.page" id="currPage"/>

@{
    if (Model != null)
    {
        @Html.HiddenFor(m => m.RecordNo, new {id = "recNo"})
        <div class="card card-primary card-outline">
            <div class="card-header p-2">
                <h3 class="card-title">
                    <i class="nav-icon fal fa-file-medical-alt"> </i>
                    Patient Record
                </h3>
                <div class="card-tools">
                

                    <button type="button" class="btn btn-tool" data-toggle="tooltip" id="return_to_list" title="Return to List">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>

            <!--card header-->

            <div class="card-body p-0 m-0">
                
                <div class="mailbox-read-info pl-2 bg-info clearfix">
                    
                        <div class="user-block m-0 p-1" style="width:100%;" id="medrecDetails">
                            <span class="text-white texthead m-0 p-0">Subjective: </span>
                            <span class="texticon iconmedDetails pull-right m-0 p-0" style="text-align:right;visibility:hidden;">

                                @{
                                    if (Model.RecordDetails != null)
                                    {
                                        <button type="button" class="btn btn-flat btn-xs" id="btn-modifymedication" title="Modify Medication">
                                            <i class="far fa-edit fa-fw text-white"></i>
                                        </button>
                                    }
                                   
                                }

                               
                            </span>
                        </div>


                    @*<h6><span class="mailbox-read-info">@Model.RecordDate.Value.ToString("yy-MMM-dd ddd tt")</span></h6>*@
                </div>


                <div class="subjective-message with-border border-bottom">

                    @(new HtmlString(Model.RecordDetails))

                </div>



                <div class="mailbox-read-info pl-2 bg-info clearfix">

                    <div class="user-block m-0 p-1" style="width:100%;" id="medication">
                        @{
                           var hasrecordMedication = Model.Medications.Count > 0 ? "disabled" : "";
                        }

                        <span class="text-white texthead m-0 p-0">Current Medication: </span>
                        <span class="texticon iconmedication pull-right m-0 p-0" style="text-align:right;visibility:hidden;">
                            <button type="button" class="btn btn-flat btn-xs" id="newmedication" title="Add Medication" @hasrecordMedication>
                                <i class="far fa-plus-square fa-fw text-white"></i>
                            </button>
                            <button type="button" class="btn btn-flat btn-xs" id="btnmodifymedication" title="Modify Medication">
                                <i class="fas fa-edit fa-fw text-white"></i>
                            </button>
                            <button type="button" class="btn btn-flat btn-xs" id="removeMedication" title="Remove Medication">
                                <i class="fas fa-trash fa-fw  text-white"></i>
                            </button>
                        </span>
                    </div>


                  
                </div>
                <div class="subjective-message with-border border-bottom">

                    <!-- medication here -->
                    @{
                        Html.RenderAction("GetMedicationView", "PatientMedicalRecord", new { area = "Doctor", recNo = Model.RecordNo });
                    }


                </div>


                <div class="mailbox-read-info pl-2 bg-info clearfix">

                    <div class="user-block m-0 p-1" style="width:100%;" id="prescription" >
                       

                        <span class="text-white texthead m-0 p-0">Prescription: </span>
                        <span class="texticon iconprescription pull-right m-0 p-0" style="text-align:right;visibility:hidden;">
                            <button type="button" class="btn btn-flat btn-xs btn-x" id="btn-newprescription" title="Add Prescription">
                                <i class="far fa-plus-square fa-fw text-white"></i>
                            </button>
                            <button type="button" class="btn btn-flat btn-xs btn-x" disabled="disabled" id="btn-modifyPrescription" title="Edit Prescription">
                                <i class="fas fa-edit fa-fw text-white"></i>
                            </button>
                            <button type="button" class="btn btn-flat btn-xs btn-x" disabled="disabled" id="btn-prescriptionremove" title="Remove Prescription">
                                <i class="fas fa-trash fa-fw  text-white"></i>
                            </button>

                            <button type="button" class="btn btn-flat btn-xs btn-x" id="printPrescription" title="Print Prescription">
                                <i class="fas fa-print fa-fw  text-white"></i>
                            </button>

                        </span>
                    </div>



                </div>

                <div class="subjective-message with-border border-bottom table-responsive p-0" id="med_prescription">

                    @{

                        Html.RenderAction("GetMedPrescription","PatientMedicalRecord",new {area="Doctor",recordNo=Model.RecordNo});

                    }


                </div>

            </div>

        </div>
       
    }
    else
    {
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="nav-icon fal fa-file-medical-alt"> </i>
                    Patient Record
                </h3>
                <div class="card-tools">

                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" id="return_to_list" data-container="body" title="Return to List">
                        <i class="fas fa-reply"></i>
                    </button>
                </div>
            </div>
            
            <div class="card-body p-0" style="min-height: 250px;">
                    
            </div>
        </div>
    }
}

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_MedHistory_paging.cshtml
<span>Page</span>
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
<span>of</span>
@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("MedicalHistory", new { area = "Doctor", page = page, id = ViewBag.patId, phyId = ViewBag.phyId }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "docmedicalrecord" }))

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_MedicalPrescription.cshtml
@using PMIS.ViewModels
@model DocPrescriptionViewModel

<div class="container-fluid">
    @using (Html.BeginForm("AddNewDoctorsPrescription","PatientMedicalRecord",FormMethod.Post,new {role="form",id="form-addDorctorPrescription"}))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.RecNo,new {id="addMedRecNo"})

        <div class="row">
            <div class="col-lg">

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Search Category:</label>
                    <div class="col-sm-4">
                        @Html.DropDownListFor(m => m.CatId, Model.PrescriptionCatListItem, new {@class = "form-control custom-select", @id = "selectlist-category"})
                    </div>
                </div>


                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Recipe (Rx):</label>
                    <div class="col-sm-8">
                        @Html.DropDownListFor(m=>m.PrescId,Model.RecipeListItem,new {@class= "form-control custom-select",@id="docrecipelistitem"})
                 
                    </div>
                </div>


                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Signatura (Sig):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Sig, new {@class = "form-control"})
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Dispensing Instructions (Disp):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.DispInst, new {@class = "form-control"})
                    </div>
                </div>

                @*<div class="form-group row">
                <label class="col-sm-2 col-form-label">Signatura (Sig):</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" value="" />
                </div>
            </div>*@


            </div>
        </div>

        <div class="row">

            <div class="col-md-6 offset-md-4">
                <button type="button" class="btn btn-primary" id="btn-saveDoctorsPrescription">Save </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
        </div>
    
    }

   
    

</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_ModifyMedicalPrescription.cshtml
@using PMIS.ViewModels
@model DocPrescriptionViewModel

<div class="container-fluid">
    @using (Html.BeginForm("UpdateMedicalPrescription", "PatientMedicalRecord", FormMethod.Post, new { role = "form", id = "form-updateDorctorPrescription" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.PrescNo)
        @Html.HiddenFor(m => m.RecNo, new { id = "addMedRecNo" })

        <div class="row">
            <div class="col-lg">

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Search Category:</label>
                    <div class="col-sm-4">
                        @Html.DropDownListFor(m => m.CatId, Model.PrescriptionCatListItem, new { @class = "form-control custom-select", @id = "selectlist-category" })
                    </div>
                </div>


                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Recipe (Rx):</label>
                    <div class="col-sm-8">
                        @Html.DropDownListFor(m => m.PrescId, Model.RecipeListItem, new { @class = "form-control custom-select", @id = "docrecipelistitem" })

                    </div>
                </div>


                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Signatura (Sig):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Sig, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Dispensing Instructions (Disp):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.DispInst, new { @class = "form-control" })
                    </div>
                </div>



            </div>
        </div>

        <div class="row">

            <div class="col-md-6 offset-md-4"> 
                <button type="button" class="btn btn-primary" id="btn-UpdateDoctorsPrescription">Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
        </div>

    }




</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_ModifyMedication.cshtml
@using PMIS.ViewModels
@model MedicationViewModel

<div class="container-fluid" style="min-height: 350px;">

    @using (Html.BeginForm("UpdateMedication", "PatientMedicalRecord", FormMethod.Post, new { role = "form", id = "form_docUpdateMedication" }))
    {

        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.RecordNo, new { @id = "recNo" })
        @Html.HiddenFor(m => m.operation)

        <div class="row">
            <div class="col-lg">

                <div class="form-group">

                    @Html.TextAreaFor(m => m.Medication, new { @class = "form-control", @id = "compose-medication", rows = "5", style = "resize:none;" })
                </div>


            </div>
        </div>

        <div class="row">
            <div class="col-lg-5 offset-5">
                <button type="submit" class="btn btn-primary" id="update-docmedication"><i class="far fa-envelope"></i> Update </button>
                <button type="reset" class="btn btn-default" id="modalClose"><i class="fas fa-times"></i> Discard</button>

            </div>
        </div>
    }


</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_ModifyPatientRecord.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-lg">
            
        </div>
    </div>
</div>

PMIS/Areas/Doctor/Views/PatientMedicalRecord/_RecordListPartialView.cshtml
@using PagedList
@using PagedList.Mvc
@using PMIS.Model
@using PMIS.HelperClass

@model PagedList<MedicalRecord>


<div class="medical-history_content">


    @{
        foreach (var item in Model)
        {

            <div class="post" data-postId="@item.RecordNo">

                <div class="user-block">

                    <span class="texthead">
                        <b>@(Utilities.capfirstletter(item.ActivityName))</b>
                    </span>

                    @{
                        int _days = DateTime.Now.Subtract(item.RecordDate.Value).Days;

                        var noofdayspass = _days > 0 ? "(" + _days + " days ago )" : " ";

                    }




                    <span class="description pull-right" id="daterecorded"> @($"{item.RecordDate.Value.ToString("MMMM dd, yyyy")}  {noofdayspass} ")</span>


                </div>
                <!-- /.user-block -->

                <div class="medical-history">
                    @(new HtmlString(item.RecordDetails))
                </div>
                <div class="mailbox-controls text-left">

                    <a href="#" class="link-chart text-sm mr-2" id="viewmedicalchartdetail"><i class="fas fa-binoculars mr-1"></i> View</a>

                </div>
            </div>
        <!-- END POST -->
        }



    }


</div>

<div class="history_paging_container">
    @*<span>Page</span>
        @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        <span>of</span>
        @Model.PageCount*@
    @Html.PagedListPager(Model, page => Url.Action("MedicalHistory", new { area = "Doctor", page = page, id = ViewBag.patId, phyId = ViewBag.phyId }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "docmedicalrecord" }))

</div>