PMIS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PMIS.Hubs;
using PMIS.Model;
using PMIS.ServiceLayer;
using PMIS.ViewModels;

namespace PMIS.Controllers
{
    public class DashboardController : Controller
    {

        private readonly IAppointmentServices _appointmentServices;
        private readonly IPatientServices _patientServices;
        private readonly IPrescriptionServices _prescriptionServices;
        private AppointHub appointHub;
        private readonly ApplicationDbContext _context = new ApplicationDbContext();


        public DashboardController(IAppointmentServices appointmentServices, IPatientServices patientServices, IPrescriptionServices prescriptionServices)
        {
            _appointmentServices = appointmentServices;
            _patientServices = patientServices;
            _prescriptionServices = prescriptionServices;
        }

        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> GetAppointments()
        {
            var dashboard = new DashBoardViewModel();
            var appointments = await _appointmentServices.GetAllAppointmentList();

            int count = 0;
            foreach (var t in appointments)
            {
                if (t.AppointDate.Date == DateTime.Today.Date) count++;
            }
            int appointmentCount = count>0? count:0;

            dashboard.appointmentCount = appointmentCount;



            return PartialView("_GetAppointments", dashboard);
        }

        [HttpGet]
        public ActionResult GetLoggedPhysician()
        {
            appointHub = new AppointHub();

            var loggedUsers= appointHub.GetAllLoggedUsers();

            //var userlist = loggedUsers.Select(t => t.UserId).ToList();

            var dashboard = new DashBoardViewModel {loggedPhysician = loggedUsers.Count};

            return PartialView("_GetLoggedPhysician", dashboard);
        }





        [HttpGet]
        public async Task<ActionResult> GetRegisteredPatients()
        {
            int patientCount = await _patientServices.CountAllPatients();

            var dashboard = new DashBoardViewModel { registeredPatients = patientCount> 0?patientCount:0};
            return PartialView("_GetRegisteredPatients",dashboard);
        }


        public async Task<ActionResult> GetMedicines()
        {
            int prescription = await _prescriptionServices.PrescriptionCount();
            var dashboard = new DashBoardViewModel { medicineCount = prescription > 0 ? prescription : 0 };
            return PartialView("_GetMedicines", dashboard);
        }
    }
}

PMIS/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PMIS.HelperClass;
using PMIS.Model;
using PMIS.ServiceLayer;
using PMIS.ViewModels;

namespace PMIS.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        private readonly IPatientServices _patientServices;
        private readonly IAppointmentServices _appointmentServices;
        private readonly IUnitOfWork _unitofwork;
        public PatientController(IPatientServices patientServices,IAppointmentServices appointmentServices, IUnitOfWork unitofwork)
        {
            this._patientServices = patientServices;
            this._unitofwork = unitofwork;
            this._appointmentServices = appointmentServices;
        }

        // GET: Patient
        public ActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAllPatientsAsync()
        {
            var patientlist = await _patientServices.GetAllPatients();

            return Json(new { data = patientlist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetPatientAutoComplete(string query)
        {

            var patients = _patientServices.GetPatientAutoComplete().Where(t => t.PatientName.Contains(query))
                .OrderBy(t => t.PatientName).Take(10).ToList();

            return Json(patients, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreatePatientProfile()
        {

            var patientModel = new PatientDetailsViewModel
            {
                GenderDictionary = _patientServices.GetGenderDictionary()

            };


            return View(patientModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePatientProfile(PatientDetailsViewModel patientDetails)
        {
            if (!ModelState.IsValid)
            {
                patientDetails.GenderDictionary = _patientServices.GetGenderDictionary();

                return View(patientDetails);
            }

            DateTime dateofBirth = new DateTime(patientDetails.yearint, patientDetails.monthint, patientDetails.dateint);

            var patient = new Patient()
            {
                Pat_Id = Utilities.GeneratePatientId(),
                Firstname = patientDetails.Firstname,
                Lastname = patientDetails.Lastname,
                Middle = patientDetails.Middle,
                DoB = dateofBirth,
                DateRegister = DateTime.Now,
                AddStreetBrgy = patientDetails.AddStreetBrgy,
                Muncity = patientDetails.Municipality,
                Province = patientDetails.Province,
                Gender = patientDetails.Gender,
                ContactCell = patientDetails.ContactCell

            };

            _patientServices.InsertPatient(patient);
            _unitofwork.Commit();

            var patId = patient.Pat_Id;
            // var url = @Url.Action("ViewProfile", "Patient");
            return Json(new { success = true, patId }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemovePatientProfile(string patientId)
        {
            var success = false;
            var patient = _patientServices.GetPatientById(patientId);

            if (patient != null)
            {
                _patientServices.RemovePatient(patient);
                _unitofwork.Commit();

                success = true;
            }

            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditPatient()
        {
            var patient = _patientServices.GetPatientById(RouteData.Values["id"].ToString());
     
            return View(patient);
        }

        [ChildActionOnly]
        public PartialViewResult GetBasicInfo(Patient patient)
        {
           
            var patientdetail=new PatientDetailsBasicInfoViewModel()
            {
                PatientId = patient.Pat_Id,
                Firstname = patient.Firstname,
                Lastname = patient.Lastname,
                Middle = patient.Middle,
                Gender = patient.Gender,
                AddStreetBrgy = patient.AddStreetBrgy,
                Municipality = patient.Muncity,
                Province = patient.Province,
                ContactCell = patient.ContactCell,
                monthint = patient.DoB?.Month ?? DateTime.Now.Month,
                dateint = patient.DoB?.Day ?? DateTime.Now.Day,
                yearint = patient.DoB?.Year ?? DateTime.Now.Year,

                GenderDictionary = _patientServices.GetGenderDictionary()
            };

            return PartialView("_EditBasicInfoPartialView", patientdetail);
        }

        [ChildActionOnly]
        public PartialViewResult GetAdvanceInfo(Patient patient)
        {
            var patientadvnceinfo = new PatientDetailsAdvanceInfoViewModel()
            {
                PatientId = patient.Pat_Id,
                CivilStat = patient.CivilStat,
                CivilStatDictionary = _patientServices.Generate_CivilStatus_Dictionary()
            };

            return PartialView("_EditAdvanceInfoPartialView", patientadvnceinfo);
        }



        [ActionName("EditBasic")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPatient(PatientDetailsBasicInfoViewModel patientBasic)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_EditBasicInfoPartialView", patientBasic);
            }


            var patientbasicinfo = _patientServices.GetPatientById(patientBasic.PatientId);

                patientbasicinfo.Firstname = patientBasic.Firstname;
                patientbasicinfo.Lastname = patientBasic.Lastname;
                patientbasicinfo.Middle = patientBasic.Middle;
                patientbasicinfo.DoB = new DateTime(patientBasic.yearint, patientBasic.monthint, patientBasic.dateint);
                patientbasicinfo.AddStreetBrgy = patientBasic.AddStreetBrgy;
                patientbasicinfo.Muncity = patientBasic.Municipality;
                patientbasicinfo.Province = patientBasic.Province;
                patientbasicinfo.Gender = patientBasic.Gender;
                patientbasicinfo.ContactCell = patientBasic.ContactCell;


            _patientServices.UpdatePatient(patientbasicinfo);
            _unitofwork.Commit();


            return Json(new {success = true}, JsonRequestBehavior.AllowGet);
        }


        [ActionName("EditAdvance")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPatient(PatientDetailsAdvanceInfoViewModel patientAdvance)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_EditAdvanceInfoPartialView", patientAdvance);
            }


            var patientdetailsAdvanceinfo = _patientServices.GetPatientById(patientAdvance.PatientId);

            patientdetailsAdvanceinfo.CivilStat = patientAdvance.CivilStat;
            patientdetailsAdvanceinfo.ContactPhone = patientAdvance.ContactTell;
            patientdetailsAdvanceinfo.Height = patientAdvance.Height;
            patientdetailsAdvanceinfo.Weight = patientAdvance.Weight;
            patientdetailsAdvanceinfo.Occupation = patientAdvance.Occupation;
            patientdetailsAdvanceinfo.Company = patientAdvance.Company;
            patientdetailsAdvanceinfo.BType = patientAdvance.BloodType;
            patientdetailsAdvanceinfo.GuardianName = patientAdvance.GuardianName;
            patientdetailsAdvanceinfo.GuardianContact = patientAdvance.GuardianContact;
            patientdetailsAdvanceinfo.GuardianRelation = patientAdvance.GuardianRelation;

            _patientServices.UpdatePatient(patientdetailsAdvanceinfo);
            _unitofwork.Commit();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> ViewProfile(string id)
        {
            var patientprofile = new PatientProfileViewModel()
            {
                PatientId = id,
                PatientDetails =await _patientServices.GetPatientDetailsById(id),
                Listofdoctors = _patientServices.GetDoctorsByPatient(id),
                Lastvisited = _appointmentServices.LastVisited(id)
            };

        
            return View(patientprofile);
        }


        [HttpGet]
        public ActionResult ProfileImageModal()
        {
           
            return PartialView("ProfileImageModal");
        }

        [HttpPost]
        public ActionResult SaveProfileImage(ProfileImageViewModel viewModel)
        {
            string randomFileName = null;
            bool _success = false;
            if (viewModel != null)
            {
                var t = viewModel.base64Image.Substring(23);
                byte[] bytes = Convert.FromBase64String(t);

                using (MemoryStream ms = new MemoryStream(bytes))
                {
                    var image = Image.FromStream(ms);

                     randomFileName = Guid.NewGuid().ToString().Substring(0, 7) + ".jpg";
                     var fullPath = Path.Combine(Server.MapPath("~/Content/Images/"), randomFileName);
                     image.Save(fullPath, System.Drawing.Imaging.ImageFormat.Jpeg);
                }

                //save image filename to database

                var patientinfo = _patientServices.GetPatientById(viewModel.patId);

                patientinfo.Image = randomFileName;

                _patientServices.UpdatePatient(patientinfo);
                _unitofwork.Commit();


                _success = true;
            }

PMIS/Controllers/PhysicianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMIS.Model;
using PMIS.ServiceLayer;
using PMIS.ViewModels;

namespace PMIS.Controllers
{
    [Authorize]
    public class PhysicianController : Controller
    {
        
        private readonly IPhycisianServices _phycisianservices;
        private readonly IUnitOfWork _unitOfWork;
        public PhysicianController(IPhycisianServices physervices,IUnitOfWork iunitofwork)
        {
            this._phycisianservices = physervices;
            this._unitOfWork = iunitofwork;
        }
        // GET: Physician
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllPhysician()
        {
            return Json(new {data = _phycisianservices.GetAllPhysician()},JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreatePhysician()
        {
            return PartialView("_CreatePhysician");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePhysician(PhysicianDetailsViewModel physicianDetails)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_CreatePhysician");
            }
            Physician physician = new Physician()
            {
                Phys_Fullname = physicianDetails.PhysName,
                Phys_Abr = physicianDetails.PhysAbr

            };

            _phycisianservices.AddPhysician(physician);
            _unitOfWork.Commit();

            return Json(new {success=true},JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult RemovePhysician(int id)
        {
            bool success = false;

            var physician = _phycisianservices.GetPhysician_By_Id(id);

            if (physician != null)
            {
                try
                {
                    _phycisianservices.RemovePhysician(physician);
                    _unitOfWork.Commit();
                    success = true;
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
            };

            return Json(new {success=success}, JsonRequestBehavior.AllowGet);
        }

      
       
    }
}

PMIS/Views/Shared/Container.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PMIS/Views/Shared/NavBar.cshtml
<nav class="main-header navbar navbar-expand navbar-dark navbar-teal">
    @if (Request.IsAuthenticated)
    {
          <!-- Left navbar links -->
        <ul class=" navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            @*<li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>*@
        </ul>
          <!-- SEARCH FORM -->
        @*<form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>*@
    }


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        @{
            Html.RenderAction("UserLogIn", "Account");
        }

    </ul>
</nav>

PMIS/Views/Shared/ReportContainer.cshtml
@using PMIS.ViewModels
@model ReportOptionViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title></title>

    <link href="~/Content/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/Content/customcss/pmis_css.css" rel="stylesheet" />
</head>
<body>

    @if (Request.IsAuthenticated)
    {
        <div class="row">
            <div class="col-md-12">
                <div id="frameholder" style="display: block;">
                    <iframe id="ReportFrame" src="" onload="document.getElementById('spinn-loader').style.display = 'none';" width="100%" height="1000" style="border: none"></iframe>
                </div>

            </div>
        </div>
    }

    <div id="spinn-loader">
        Loading data Pls. wait....
    </div>
    
    @Html.HiddenFor(m=>m.recordNo,new {id="recordNo"})
    

<script src="~/Content/plugins/jquery/jquery.min.js"></script>

<script type="text/javascript">

    $('#spinn-loader').show();

    var recordNo = document.getElementById('recordNo').value;


    $("#ReportFrame").attr("src", "@Url.Content("~/Reports/ReportViewer/Prescription.aspx")");

</script>


</body>
</html>

PMIS/Views/Shared/SideBar_Left.cshtml
@using Microsoft.AspNet.Identity

<!-- Sidebar -->
<div class="sidebar">
    
    @if (Request.IsAuthenticated)
    {

        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="@Url.Content("~/Content/dist/img/user.jpg")" class="img-circle elevation-2" alt="User Image">
            </div>

           @{
               Html.RenderAction("GetInfoLogInUser","Account",new {userId=User.Identity.GetUserId()});
           }
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Dashboard")" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            @*<i class="right fas fa-angle-left"></i>*@
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Patient")" class="nav-link">
                        <i class="nav-icon fas fa-procedures"></i>
                        <p>
                            Patients
                        </p>
                    </a>
                </li>
                @*<li class="nav-item">
                    <a href="@Url.Action("Index", "Physician")" class="nav-link">
                        <i class="nav-icon far fa-user-md"></i>
                        <p>
                            Physician
                        </p>
                    </a>
                </li>*@

                <li class="nav-item">
                    <a href="@Url.Action("Index", "Appointment")" class="nav-link">
                        <i class="nav-icon fad fa-calendar-check"></i>
                        <p>
                            Appointment
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index", "PatientRecord")" class="nav-link">
                        <i class="nav-icon fal fa-file-medical-alt"></i>
                        <p>
                            Medical Records
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Prescription")" class="nav-link">
                        <i class="nav-icon fal fa-prescription "></i>
                        <p>
                            Prescriptions
                        </p>
                    </a>
                </li>
                @if (this.User.IsInRole("admin"))
                {
                    <li class="nav-item">
                        <a href="@Url.Action("UsersIndex", "Account")" class="nav-link">
                            <i class="nav-icon fal fa-user-alt"></i>
                            <p>
                                Users
                            </p>
                        </a>
                    </li>
                }
                

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    }

</div>

PMIS/Views/Shared/_Content_Header.cshtml
 <!-- Content Header (Page header) -->
<section class="content-header">
    
</section>

PMIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Patient Informations System </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="~/Content/dist/img/PMIS.png" />
    @Styles.Render("~/Styles/Css")
    @Styles.Render("~/adminstyle")
  
    <link href="@Url.Content("~/Content/plugins/summernote/summernote-bs4.css")" rel="stylesheet" />

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <!-- Navbar -->
        @Html.Partial("NavBar")
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link navbar-warning">
                <img src="@Url.Content("~/Content/dist/img/PMIS.png")"
                     alt="PMIS v2.0"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-bold text-black-50">PMIS</span>
            </a>
            
            @Html.Partial("SideBar_Left")

            <!-- /.sidebar -->
        </aside>
        
        

        <!-- Content Wrapper. Contains page content -->
        
       
        <div class="content-wrapper">
            
        @if (Request.IsAuthenticated)
        {
            @Html.Partial("_Content_Header")
        }

            <section class="content">

                @if (Request.IsAuthenticated)
                {
                    @RenderBody()
                }
               

            </section>

          
        </div>

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.1
            </div>
            <strong>PMIS.@DateTime.Now.Year</strong>
        </footer>

    </div>
<!-- ./wrapper -->
    
    <div id="spinn-loader">
        @*Loading data Pls. wait....*@
    </div>
    

    @Scripts.Render("~/bundles/javascript")

    @Scripts.Render("~/bundles/AjaxExtensions")
    
    @*@Scripts.Render("~/scriptbundles/fullcalendarjs")*@
    
    
    <script type="text/javascript" src="@Url.Content("~/Content/signalR/jquery.signalR-2.4.1.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/signalr/hubs")"></script>

    <script type="text/javascript" src="@Url.Content("~/Scripts/js_signalAppointment.js")"></script>
    

    @RenderSection("scripts", required: false)
    
<script type="text/javascript">

    const toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 5000
    });


    $(document).ready(function() {
        //debugger;
        var url = window.location;

        var controller = url.pathname.split('/')[1];

        //console.log(controller);

        $('ul.nav-sidebar a').removeClass('active');

        $('ul.nav-sidebar a').filter(function() {

            //console.log(this.pathname.split('/')[1]);

            return this.pathname.split('/')[1] === controller;

        }).addClass('active');

        $('ul.nav-treeview a').filter(function() {

            return this.pathname.split('/')[1] == controller;


        }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');




    });


    $(document).on('keypress', '.number-only', function (event) {

        if ((event.which !== 46 || $(this).val().indexOf('.') !== -1) && (event.which < 48 || event.which > 57) && (event.which !== 48)) {
            event.preventDefault();
        }
    });

</script>

    <script src="@Url.Content("~/Content/plugins/summernote/summernote-bs4.min.js")"></script>
</body>
</html>

PMIS/Views/Shared/_LogUserPartialView.cshtml
@using Microsoft.AspNet.Identity
@model PMIS.ViewModels.UsersViewModel


@if (Request.IsAuthenticated)
{
    <!-- User Dropdown Menu -->

    <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            <img src="@Url.Content("~/Content/dist/img/user.jpg")" class="user-image img-circle elevation-2" alt="User Image">
            <span class="d-none d-md-inline">@Model.username</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <!-- User image -->
            <li class="user-header bg-primary">
                <img src="@Url.Content("~/Content/dist/img/user.jpg")" class="img-circle elevation-2" alt="User Image">

                <p>
                    @Model.username - <span class="text text-center">@Model.roles</span>
                    @*<small>Member since Nov. 2012</small>*@
                </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
                <div class="row">
                    
                    <div class="col-5 text-center">
                        <a href="@Url.Action("UserProfile","Account",new{userId=Model.userId})" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    
                    <div class="col-2">
                        
                    </div>
                    
                    
                 
                        <div class="col-5 text-center">
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logout"}))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logout').submit()" class="btn btn-default btn-flat float-right">Sign out</a>
                            }
                        </div>

                    
                  
               

                </div>
                <!-- /.row -->
            </li>
          
        </ul>

    </li>
}

else
{
    <li class="nav-item d-none d-sm-inline-block">
        <a href="@Url.Action("LogIn","Account")" class="nav-link">Log-in</a>
    </li>
}